workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean & get dependencies
        script: |
          flutter clean
          flutter pub get
          flutter pub upgrade
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          cd ..
      - name: iOS Simulator Build
        script: |
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/**/*.app
