name: talabak_users
description: A food delivery app connecting users with restaurants.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.2
  smooth_page_indicator: ^1.2.1
  flutter_intl_phone_field: ^0.0.7
  lottie: ^3.3.1
  supabase_flutter: ^2.9.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  app_links: ^6.4.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  google_places_flutter: ^2.1.1
  geocoding: ^4.0.0
  http: ^1.5.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_web_auth_2: ^4.1.0
  desktop_webview_auth: ^0.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  rename: ^3.0.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/
    - assets/animations/success.json
    - assets/animations/
    - assets/icon/app_icon_New.png
    - assets/icon/app_icon_New.png

flutter_native_splash:
  color: "#25aa50"
  image: assets/icon/app_icon_New.png
  color_dark: "#25aa50"
  image_dark: assets/icon/app_icon_New.png

  android: true
  ios: true
  web: true

  android_12:
    color: "#25aa50"
    image: assets/icon/app_icon_New.png
    icon_background_color: "#25aa50"

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_New.png"
