// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjLAHfpENg0SrDNcS6CsU3YgB9l9WPn0A',
    appId: '1:495352546222:web:7612db76116d9b23023e3f',
    messagingSenderId: '495352546222',
    projectId: 'talabak-33a24',
    authDomain: 'talabak-33a24.firebaseapp.com',
    storageBucket: 'talabak-33a24.firebasestorage.app',
    measurementId: 'G-QX5758Z7WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_0CQmBEjMRA7URYfHzCyHXUQ24a_-_w',
    appId: '1:495352546222:android:e783576182e30ac7023e3f',
    messagingSenderId: '495352546222',
    projectId: 'talabak-33a24',
    storageBucket: 'talabak-33a24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBsj6WsNZVWbvCL-Opf9fua2UVIEyuBgQ',
    appId: '1:495352546222:ios:9efe6679f2745da5023e3f',
    messagingSenderId: '495352546222',
    projectId: 'talabak-33a24',
    storageBucket: 'talabak-33a24.firebasestorage.app',
    androidClientId: '495352546222-aiptg04mt44od0khotn9qlhu86tid5th.apps.googleusercontent.com',
    iosClientId: '495352546222-r7677qjomvhq799kn7kgadme7t4buph1.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBsj6WsNZVWbvCL-Opf9fua2UVIEyuBgQ',
    appId: '1:495352546222:ios:e1c9384d8f42ad6e023e3f',
    messagingSenderId: '495352546222',
    projectId: 'talabak-33a24',
    storageBucket: 'talabak-33a24.firebasestorage.app',
    androidClientId: '495352546222-aiptg04mt44od0khotn9qlhu86tid5th.apps.googleusercontent.com',
    iosClientId: '495352546222-gour7j3uhflcf0vj4jck3a8ga4sqm75n.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabakUsers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjLAHfpENg0SrDNcS6CsU3YgB9l9WPn0A',
    appId: '1:495352546222:web:6e5108985bbed6e8023e3f',
    messagingSenderId: '495352546222',
    projectId: 'talabak-33a24',
    authDomain: 'talabak-33a24.firebaseapp.com',
    storageBucket: 'talabak-33a24.firebasestorage.app',
    measurementId: 'G-P4TCEY0D1D',
  );

}